<?xml version="1.0" encoding="utf-8"?><Database Name="fixitDatabase" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\fixitDatabase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="fixitDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin" Member="admins">
    <Type Name="admin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="admin" Member="admin1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HomePage" Member="HomePages">
    <Type Name="HomePage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="logo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="firstLine" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="secoundLine" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="backgroundPic" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="websitelogo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.navbar" Member="navbars">
    <Type Name="navbar">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="home" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="services" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="about" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="team" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="contact" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Services" Member="Services">
    <Type Name="Service">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="h1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="h2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="elec" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="plum" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="carp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="E" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="P" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="C" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Team" Member="Teams">
    <Type Name="Team">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="h1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="h2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="M1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="M2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="M3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="j1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="j2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="j3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="h3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Plumbers" Member="Plumbers">
    <Type Name="Plumber">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NIC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Experience" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="uearsWorkingwithus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOfJoining" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateOfleaving" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="workerid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pic" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Carpenter" Member="Carpenters">
    <Type Name="Carpenter">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Experience" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[NIC ]" Member="NIC_" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="yearsWorkingwithus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOfJoining" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateOfleaving" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="workerId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pic" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Electritions" Member="Electritions">
    <Type Name="Electrition">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NIC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Experience" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="yearsWorkingwithus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOfJoining" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateOfleaving" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="workerId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pic" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WebsiteComments" Member="WebsiteComments">
    <Type Name="WebsiteComment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>